# Machine Learning Zoomcamp
## 1.7 Introduction to NumPy

Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
    * Summarizing operations




In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating arrays

np.zeros(5)

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.full(5, 3)

array([3, 3, 3, 3, 3])

In [5]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [6]:
a[2]

np.int64(3)

In [7]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays

In [11]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
n[2,2]

np.int64(9)

In [14]:
n[1,1]

np.int64(5)

In [15]:
n[1]

array([4, 5, 6])

In [16]:
n[2] = [1,1,1]
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [17]:
n[:,1]

array([2, 5, 1])

In [18]:
n[:,1] = [1,1,1]
n

array([[1, 1, 3],
       [4, 1, 6],
       [1, 1, 1]])

## Randomly generated arrays

In [19]:
np.random.rand(5,2)

array([[0.6172814 , 0.83048667],
       [0.61795445, 0.82843025],
       [0.0894803 , 0.32423823],
       [0.86896656, 0.64550851],
       [0.11994732, 0.60405466]])

In [20]:
np.random.rand(5,2)

array([[0.46389557, 0.67275343],
       [0.98645023, 0.64815712],
       [0.42944967, 0.44668118],
       [0.48173383, 0.18404355],
       [0.55598418, 0.46367842]])

In [24]:
np.random.seed(2)
100 * np.random.rand(5,2)


array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [23]:
np.random.seed(2)
np.random.randn(5,2)


array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [25]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))


array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [28]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [29]:
a + 1

array([1, 2, 3, 4, 5])

In [30]:
a * 2

array([0, 2, 4, 6, 8])

In [31]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. ])

In [32]:
a - 1

array([-1,  0,  1,  2,  3])

In [36]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [37]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison operations

In [40]:
a

array([0, 1, 2, 3, 4])

In [41]:
a >= 2

array([False, False,  True,  True,  True])

In [42]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [43]:
a > b

array([False, False,  True,  True,  True])

In [44]:
a[a>b]

array([2, 3, 4])

In [45]:
a[a<b]

array([0, 1])

In [48]:
a[a==b]

array([], dtype=int64)

## Summarizing operations

In [49]:
a

array([0, 1, 2, 3, 4])

In [50]:
a.max()

np.int64(4)

In [51]:
a.sum()

np.int64(10)

In [52]:
a.mean()

np.float64(2.0)

In [53]:
a.std()

np.float64(1.4142135623730951)

In [54]:
n.max()

np.int64(6)

In [55]:
n.sum()

np.int64(19)

In [56]:
n.mean()

np.float64(2.111111111111111)

In [57]:
n.std(
)

np.float64(1.7284832429004495)

In [58]:
n.min()

np.int64(1)